import { useState } from 'react';
import { BrainCircuit, Sparkles } from 'lucide-react';
import API from '../services/api';

export default function AiInsights() {
  const [insights, setInsights] = useState(null); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const analyze = async () => { setLoading(true); setError(''); try { const res = await API.post('/ai/analyze-spending'); setInsights(res.data.data.insights); } catch (err) { setError(err.response?.data?.message || 'Could not generate insights.'); } finally { setLoading(false); } };
  return <div className="mx-auto max-w-4xl space-y-6"><div><h1 className="text-2xl font-bold text-white">AI Financial Insights</h1><p className="text-sm text-slate-400">Informational analysis only — not financial or investment advice.</p></div><section className="glass-panel rounded-2xl border border-indigo-500/30 p-6"><BrainCircuit className="mb-4 w-10 h-10 text-indigo-400" /><h2 className="text-lg font-semibold text-white">Analyze this month’s spending</h2><p className="mt-2 text-sm text-slate-400">Only summarized category totals and budget data are sent for analysis. Passwords and authentication data are never included.</p><button onClick={analyze} disabled={loading} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-60"><Sparkles className="w-4 h-4" />{loading ? 'Analyzing…' : 'Analyze My Spending'}</button></section>{error && <p className="text-red-400">{error}</p>}{insights && <section className="glass-panel rounded-2xl border border-slate-800 p-6 space-y-5"><div><h2 className="font-semibold text-white">Spending summary</h2><p className="mt-2 text-sm text-slate-300">{insights.summary}</p></div><div><h2 className="font-semibold text-white">Top spending trend</h2><p className="mt-2 text-sm text-slate-300">{insights.topSpendingTrend}</p></div><div><h2 className="font-semibold text-white">Budget alerts</h2><ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-amber-300">{insights.budgetAlerts.map((item, index) => <li key={index}>{item}</li>)}</ul></div><div><h2 className="font-semibold text-white">Practical tips</h2><ul className="mt-2 list-disc space-y-1 pl-5 text-sm text-slate-300">{insights.actionableTips.map((item, index) => <li key={index}>{item}</li>)}</ul></div></section>}</div>;
}
